@startuml Kanban class diagram

left to right direction

class User {
    id : Integer
    name : String
    avatar : String
    tasks : Array[Tasks]
}

class Task {
    id : Integer
    desc : String
    status : Integer
}

class Project {
    id : Integer
    name : String
    tasks : Array[Task]
}

User --{ Task
Task }-- Project


@enduml
